return {
  ['PlaitCapabilityState'] = { 'active', 'degraded' },
  ['PlaitEffectState'] = { 'pending', 'completed', 'failed', 'skipped' },
  ['PlaitModuleState'] = { 'active' },
  ['PlaitOperationState'] = { 'pending', 'succeeded', 'failed' },
  ['PlaitOwnership'] = { 'mason', 'project', 'hybrid' },
  ['PlaitPackageInconsistency'] = {
    'checkout_without_lock',
    'lock_without_checkout',
    'malformed_metadata',
    'duplicate_metadata',
    'internal_source_mismatch',
    'internal_revision_mismatch',
    'interrupted_mutation',
  },
  ['PlaitPackageState'] = {
    'absent',
    'satisfied',
    'drifted',
    'source_collision',
    'restart_required',
    'partial_unknown',
  },
  ['PlaitReasonId'] = {
    'invalid_plan',
    'not_configured',
    'capability_inactive',
    'no_client',
    'client_unsupported',
    'no_diagnostics',
    'completion_inactive',
    'no_candidate',
    'documentation_unavailable',
    'no_formatter',
    'tool_absent',
    'tool_incompatible',
    'tool_unprobeable',
    'formatter_chain_unavailable',
    'consent_required',
    'consent_denied',
    'package_absent',
    'package_drifted',
    'package_source_collision',
    'restart_required',
    'partial_unknown',
    'environment_unavailable',
    'execution_failed',
  },
  ['PlaitSnapshotState'] = { 'validated', 'invalid', 'applied', 'unavailable', 'failed' },
  ['PlaitToolProbeFailure'] = {
    'not_regular_file',
    'not_executable',
    'broken_symlink',
    'symlink_loop',
    'outside_root',
    'timeout',
    'exit_nonzero',
    'output_limit',
    'version_missing',
  },
  ['PlaitToolState'] = { 'satisfied', 'absent', 'incompatible', 'unprobeable' },
}
